PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

  CALL SUBSCREEN %_SUBSCREEN_%_SUB%_CONTAINER
  INCLUDING 'SAPLSSEL' '2001' .

MODULE %_BUKRS.

MODULE %_ANLAGE.

MODULE %_UNTNR.

MODULE %_SO_GNJHR.

MODULE %_SO_IMAPE.

MODULE %_SO_PSPNR.

MODULE %_SO_EAUFN.

MODULE %_SO_ANLKL.

MODULE %_SO_GSBER.

MODULE %_SO_KOSTL.

MODULE %_SO_WERKS.

MODULE %_SO_STORT.

MODULE %_SO_ANLUE.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.


  CALL SUBSCREEN %_SUBSCREEN_%_SUB%_CONTAINER .

CHAIN.
  FIELD  BUKRS-LOW.
  FIELD  BUKRS-HIGH.
  MODULE %_BUKRS.
ENDCHAIN.

FIELD !PA_XANLG MODULE %_PA_XANLG .

CHAIN.
  FIELD  ANLAGE-LOW.
  FIELD  ANLAGE-HIGH.
  MODULE %_ANLAGE.
ENDCHAIN.

CHAIN.
  FIELD  UNTNR-LOW.
  FIELD  UNTNR-HIGH.
  MODULE %_UNTNR.
ENDCHAIN.

FIELD !PA_VERSN MODULE %_PA_VERSN .

FIELD !PA_XBUDG MODULE %_PA_XBUDG .

FIELD !PA_XINVP MODULE %_PA_XINVP .

FIELD !PA_PRNAM MODULE %_PA_PRNAM .

FIELD !PA_POSI1 MODULE %_PA_POSI1 .

CHAIN.
  FIELD  SO_GNJHR-LOW.
  FIELD  SO_GNJHR-HIGH.
  MODULE %_SO_GNJHR.
ENDCHAIN.

FIELD !PA_PGSEL MODULE %_PA_PGSEL .


CHAIN.
  FIELD PA_XINVP .
  FIELD PA_PRNAM .
  FIELD PA_POSI1 .
  FIELD  SO_GNJHR-LOW.
  FIELD  SO_GNJHR-HIGH.
  FIELD PA_PGSEL .
    MODULE %_BLOCK_1000012.
ENDCHAIN.

FIELD !PA_XMANF MODULE %_PA_XMANF .

CHAIN.
  FIELD  SO_IMAPE-LOW.
  FIELD  SO_IMAPE-HIGH.
  MODULE %_SO_IMAPE.
ENDCHAIN.

FIELD !PA_IMAGN MODULE %_PA_IMAGN .


CHAIN.
  FIELD PA_XMANF .
  FIELD  SO_IMAPE-LOW.
  FIELD  SO_IMAPE-HIGH.
  FIELD PA_IMAGN .
    MODULE %_BLOCK_1000019.
ENDCHAIN.

FIELD !PA_XPROJ MODULE %_PA_XPROJ .

CHAIN.
  FIELD  SO_PSPNR-LOW.
  MODULE %_SO_PSPNR.
ENDCHAIN.

FIELD !PA_POSID MODULE %_PA_POSID .


CHAIN.
  FIELD PA_XPROJ .
  FIELD  SO_PSPNR-LOW.
  FIELD PA_POSID .
    MODULE %_BLOCK_1000025.
ENDCHAIN.

FIELD !PA_XAUFT MODULE %_PA_XAUFT .

CHAIN.
  FIELD  SO_EAUFN-LOW.
  FIELD  SO_EAUFN-HIGH.
  MODULE %_SO_EAUFN.
ENDCHAIN.

CHAIN.
  FIELD PA_XSETL.
  FIELD PA_XGJBG.
    MODULE %_RADIOBUTTON_GROUP_SETL                          .
ENDCHAIN.


CHAIN.
  FIELD PA_XSETL.
  FIELD PA_XGJBG.
    MODULE %_BLOCK_1000035.
ENDCHAIN.

FIELD !PA_STSEL MODULE %_PA_STSEL .


CHAIN.
  FIELD PA_STSEL .
    MODULE %_BLOCK_1000048.
ENDCHAIN.


CHAIN.
  FIELD PA_VERSN .
  FIELD PA_XBUDG .
  FIELD PA_XINVP .
  FIELD PA_PRNAM .
  FIELD PA_POSI1 .
  FIELD  SO_GNJHR-LOW.
  FIELD  SO_GNJHR-HIGH.
  FIELD PA_PGSEL .
  FIELD PA_XMANF .
  FIELD  SO_IMAPE-LOW.
  FIELD  SO_IMAPE-HIGH.
  FIELD PA_IMAGN .
  FIELD PA_XPROJ .
  FIELD  SO_PSPNR-LOW.
  FIELD PA_POSID .
  FIELD PA_XAUFT .
  FIELD  SO_EAUFN-LOW.
  FIELD  SO_EAUFN-HIGH.
  FIELD PA_XSETL.
  FIELD PA_XGJBG.
  FIELD PA_STSEL .
    MODULE %_BLOCK_1000008.
ENDCHAIN.

CHAIN.
  FIELD  SO_ANLKL-LOW.
  FIELD  SO_ANLKL-HIGH.
  MODULE %_SO_ANLKL.
ENDCHAIN.

CHAIN.
  FIELD  SO_GSBER-LOW.
  FIELD  SO_GSBER-HIGH.
  MODULE %_SO_GSBER.
ENDCHAIN.

CHAIN.
  FIELD  SO_KOSTL-LOW.
  FIELD  SO_KOSTL-HIGH.
  MODULE %_SO_KOSTL.
ENDCHAIN.

CHAIN.
  FIELD  SO_WERKS-LOW.
  FIELD  SO_WERKS-HIGH.
  MODULE %_SO_WERKS.
ENDCHAIN.

CHAIN.
  FIELD  SO_STORT-LOW.
  FIELD  SO_STORT-HIGH.
  MODULE %_SO_STORT.
ENDCHAIN.

CHAIN.
  FIELD  SO_ANLUE-LOW.
  FIELD  SO_ANLUE-HIGH.
  MODULE %_SO_ANLUE.
ENDCHAIN.

FIELD !PA_AI_ID MODULE %_PA_AI_ID .


CHAIN.
  FIELD  SO_ANLKL-LOW.
  FIELD  SO_ANLKL-HIGH.
  FIELD  SO_GSBER-LOW.
  FIELD  SO_GSBER-HIGH.
  FIELD  SO_KOSTL-LOW.
  FIELD  SO_KOSTL-HIGH.
  FIELD  SO_WERKS-LOW.
  FIELD  SO_WERKS-HIGH.
  FIELD  SO_STORT-LOW.
  FIELD  SO_STORT-HIGH.
  FIELD  SO_ANLUE-LOW.
  FIELD  SO_ANLUE-HIGH.
  FIELD PA_AI_ID .
    MODULE %_BLOCK_1000053.
ENDCHAIN.

FIELD !AFBLPE MODULE %_AFBLPE .

FIELD !BERDATUM MODULE %_BERDATUM .

FIELD !BEREICH1 MODULE %_BEREICH1 .

FIELD !BEREICH2 MODULE %_BEREICH2 .

FIELD !BEREICH3 MODULE %_BEREICH3 .

FIELD !SRTVR MODULE %_SRTVR .

FIELD !UMVAR MODULE %_UMVAR .

CHAIN.
  FIELD XEINZEL .
  FIELD XUNTNR  .
  FIELD SUMMB   .
    MODULE %_RADIOBUTTON_GROUP_SEL1                          .
ENDCHAIN.


CHAIN.
  FIELD AFBLPE .
  FIELD BERDATUM .
  FIELD BEREICH1 .
  FIELD BEREICH2 .
  FIELD BEREICH3 .
  FIELD SRTVR .
  FIELD UMVAR .
  FIELD XEINZEL .
  FIELD XUNTNR  .
  FIELD SUMMB   .
    MODULE %_BLOCK_1000064.
ENDCHAIN.

CHAIN.
  FIELD  BUKRS-LOW.
  FIELD  BUKRS-HIGH.
  FIELD PA_XANLG .
  FIELD  ANLAGE-LOW.
  FIELD  ANLAGE-HIGH.
  FIELD  UNTNR-LOW.
  FIELD  UNTNR-HIGH.
  FIELD PA_VERSN .
  FIELD PA_XBUDG .
  FIELD PA_XINVP .
  FIELD PA_PRNAM .
  FIELD PA_POSI1 .
  FIELD  SO_GNJHR-LOW.
  FIELD  SO_GNJHR-HIGH.
  FIELD PA_PGSEL .
  FIELD PA_XMANF .
  FIELD  SO_IMAPE-LOW.
  FIELD  SO_IMAPE-HIGH.
  FIELD PA_IMAGN .
  FIELD PA_XPROJ .
  FIELD  SO_PSPNR-LOW.
  FIELD PA_POSID .
  FIELD PA_XAUFT .
  FIELD  SO_EAUFN-LOW.
  FIELD  SO_EAUFN-HIGH.
  FIELD PA_XSETL.
  FIELD PA_XGJBG.
  FIELD PA_STSEL .
  FIELD  SO_ANLKL-LOW.
  FIELD  SO_ANLKL-HIGH.
  FIELD  SO_GSBER-LOW.
  FIELD  SO_GSBER-HIGH.
  FIELD  SO_KOSTL-LOW.
  FIELD  SO_KOSTL-HIGH.
  FIELD  SO_WERKS-LOW.
  FIELD  SO_WERKS-HIGH.
  FIELD  SO_STORT-LOW.
  FIELD  SO_STORT-HIGH.
  FIELD  SO_ANLUE-LOW.
  FIELD  SO_ANLUE-HIGH.
  FIELD PA_AI_ID .
  FIELD AFBLPE .
  FIELD BERDATUM .
  FIELD BEREICH1 .
  FIELD BEREICH2 .
  FIELD BEREICH3 .
  FIELD SRTVR .
  FIELD UMVAR .
  FIELD XEINZEL .
  FIELD XUNTNR  .
  FIELD SUMMB   .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.

PROCESS ON VALUE-REQUEST.
  FIELD PA_PRNAM MODULE %_PA_PRNAM_VAL .
  FIELD PA_POSI1 MODULE %_PA_POSI1_VAL .
  FIELD BEREICH1 MODULE %_BEREICH1_VAL .
  FIELD BEREICH2 MODULE %_BEREICH2_VAL .
  FIELD BEREICH3 MODULE %_BEREICH3_VAL .