PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZGIT_SKA1 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZGIT_SKA1-KTOPL .
    FIELD ZGIT_SKA1-SAKNR .
    FIELD ZGIT_SKA1-XBILK .
    FIELD ZGIT_SKA1-SAKAN .
    FIELD ZGIT_SKA1-BILKT .
    FIELD ZGIT_SKA1-ERNAM .
    FIELD ZGIT_SKA1-GVTYP .
    FIELD ZGIT_SKA1-KTOKS .
    FIELD ZGIT_SKA1-ZZHKONT .
    FIELD ZGIT_SKA1-ZZKOSTL .
    FIELD ZGIT_SKA1-ZZXBLNR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZGIT_SKA1-KTOPL .
    FIELD ZGIT_SKA1-SAKNR .
    FIELD ZGIT_SKA1-XBILK .
    FIELD ZGIT_SKA1-SAKAN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.