PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZGIT_SKA1-KTOPL .
    FIELD ZGIT_SKA1-SAKNR .
    FIELD ZGIT_SKA1-XBILK .
    FIELD ZGIT_SKA1-SAKAN .
    FIELD ZGIT_SKA1-BILKT .
    FIELD ZGIT_SKA1-ERDAT .
    FIELD ZGIT_SKA1-ERNAM .
    FIELD ZGIT_SKA1-GVTYP .
    FIELD ZGIT_SKA1-KTOKS .
    FIELD ZGIT_SKA1-ZZHKONT .
    FIELD ZGIT_SKA1-ZZKOSTL .
    FIELD ZGIT_SKA1-ZZXBLNR .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZGIT_SKA1-KTOPL .
    FIELD ZGIT_SKA1-SAKNR .
    FIELD ZGIT_SKA1-XBILK .
    FIELD ZGIT_SKA1-SAKAN .
  module detail_pai.
 endchain.