*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZGIT_SKA1U01.
                    "TABLEFRAME_ZGIT_SKA1
INCLUDE LZGIT_SKA1U02.
                    "TABLEPROC_ZGIT_SKA1