class ZCL_ZODATA_BILLOFMATER_MPC definition
  public
  inheriting from /IWBEP/CL_MGW_PUSH_ABS_MODEL
  create public .

public section.

  interfaces IF_SADL_GW_MODEL_EXPOSURE_DATA .

  types:
    begin of TS_DISPLAYIMPACTCHART,
        SCENARIO_NAME type string,
        APP_BO type string,
    end of TS_DISPLAYIMPACTCHART .
  types:
   begin of ts_text_element,
      artifact_name  type c length 40,       " technical name
      artifact_type  type c length 4,
      parent_artifact_name type c length 40, " technical name
      parent_artifact_type type c length 4,
      text_symbol    type textpoolky,
   end of ts_text_element .
  types:
         tt_text_elements type standard table of ts_text_element with key text_symbol .
  types:
    begin of TS_CHECKVERSIONCONTROL,
        BILLOFMATERIALVARIANTUSAGE type STLAN,
    end of TS_CHECKVERSIONCONTROL .
  types:
    begin of TS_CREATECHANGENUMBER,
        DRAFTUUID type SYSUUID_X,
        AENNR type string,
        DATUV type TIMESTAMP,
        AETXT type string,
    end of TS_CREATECHANGENUMBER .
  types:
    begin of TS_FILTERPARAMETEREFFECTIVITY,
        PLANT type C length 4,
        MATERIAL type C length 40,
        ENGINEERINGCHANGEDOCUMENT type C length 12,
        BILLOFMATERIALVERSION type C length 4,
        BILLOFMATERIALVARIANT type C length 2,
        BILLOFMATERIALCATEGORY type C length 1,
        BILLOFMATERIAL type C length 8,
        PARAMETERS type string,
    end of TS_FILTERPARAMETEREFFECTIVITY .
  types:
    begin of TS_CHECKMANDATORYCRASSIGNMENT,
        PLANT type string,
        MATERIAL type string,
        CHANGERECORD type string,
        BILLOFMATERIALVARIANTUSAGE type string,
    end of TS_CHECKMANDATORYCRASSIGNMENT .
  types:
     TS_IMPACTANALYSISNODE type IMC_S_NODE .
  types:
TT_IMPACTANALYSISNODE type standard table of TS_IMPACTANALYSISNODE .
  types:
     TS_IMPACTANALYSISSCENARIO type IMC_S_SCENARIO .
  types:
TT_IMPACTANALYSISSCENARIO type standard table of TS_IMPACTANALYSISSCENARIO .
  types:
  begin of TS_VERSIONCONTROL,
     ISSUCCESSIONVERSION type FLAG,
  end of TS_VERSIONCONTROL .
  types:
TT_VERSIONCONTROL type standard table of TS_VERSIONCONTROL .
  types:
     TS_CHANGENUMBER type ICHANGENUMBERS .
  types:
TT_CHANGENUMBER type standard table of TS_CHANGENUMBER .
  types:
  begin of TS_ENGINEERINGCHANGEDOCUMENT,
     ENGINEERINGCHANGEDOCUMENT type C length 12,
  end of TS_ENGINEERINGCHANGEDOCUMENT .
  types:
TT_ENGINEERINGCHANGEDOCUMENT type standard table of TS_ENGINEERINGCHANGEDOCUMENT .
  types:
  begin of TS_EFFECTIVITYPARAMETERS,
     FIELDNAME type C length 30,
     FIELDLABEL type C length 30,
  end of TS_EFFECTIVITYPARAMETERS .
  types:
TT_EFFECTIVITYPARAMETERS type standard table of TS_EFFECTIVITYPARAMETERS .
  types:
  begin of TS_ADDITIONALCONTROLDATA,
     ISUSAGEENGINEERINGRELEVANT type string,
     FIXEDITEMCATEGORY type string,
     BILLOFMATERIALITEMCATEGORYDESC type string,
     BILLOFMATERIALITEMCATEGORY type string,
     ISDISPLAYONLY type FLAG,
     ISFEATUREACTIVE type FLAG,
     ISCLOUDSYSTEM type FLAG,
     ISBOMVERSIONINACTIVE type FLAG,
     BOMUSAGEVERSIONCONTROL type string,
     BOMUSAGESFORMANUALVERSION type string,
     ISPRELIMINARYITEMCATEGORY type string,
  end of TS_ADDITIONALCONTROLDATA .
  types:
TT_ADDITIONALCONTROLDATA type standard table of TS_ADDITIONALCONTROLDATA .
  types:
  begin of TS_MANDATORYCRASSIGNMENT,
     ISCHANGERECORDMANDT type FLAG,
  end of TS_MANDATORYCRASSIGNMENT .
  types:
TT_MANDATORYCRASSIGNMENT type standard table of TS_MANDATORYCRASSIGNMENT .
  types:
    begin of TS_C_BILLOFMATERIALITEMTPTYPE.
      include type C_BILLOFMATERIALITEMTP.
  types:
      HASDRAFTENTITY type SDRAFT_FIELDS-HASDRAFTENTITY,
      DRAFTUUID type SDRAFT_FIELDS-DRAFTUUID,
      PARENTDRAFTUUID type SDRAFT_FIELDS-PARENTDRAFTUUID,
      DRAFTENTITYCREATIONDATETIME type SDRAFT_FIELDS-DRAFTENTITYCREATIONDATETIME,
      DRAFTENTITYLASTCHANGEDATETIME type SDRAFT_FIELDS-DRAFTENTITYLASTCHANGEDATETIME,
      HASACTIVEENTITY type SDRAFT_FIELDS-HASACTIVEENTITY,
      ISACTIVEENTITY type SDRAFT_FIELDS-ISACTIVEENTITY,
      DRAFTENTITYOPERATIONCODE type SDRAFT_FIELDS-DRAFTENTITYOPERATIONCODE,
      A_PREPARATION type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_REFRESH type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_VALIDATION type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      F_ALTERNATIVEITEMGROUP type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ALTERNATIVEITEMPRIORITY type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ALTERNATIVEITEMSTRATEGY type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BILLOFMATERIALCOMPONENT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BILLOFMATERIALITEMCATEGORY type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BILLOFMATERIALITEMNUMBER type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BILLOFMATERIALITEMQUANTITY type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BILLOFMATERIALITEMUNIT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BILLOFMATERIALVERSIONFOREDIT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BOMITEMCATEGORYFOREDIT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BOMITEMDESCRIPTION type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BOMITEMHASFIXEDQUANTITY type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BOMITEMISCOSTINGRELEVANT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BOMITEMISPLANTMAINTRELEVANT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BOMITEMISSALESRELEVANT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BOMITEMISSPAREPART type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BOMITEMSORTER type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BOMITEMTEXT2 type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_CLASSNUMBER type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_CLASSTYPE type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_COMPONENTDESCRIPTION type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_COMPONENTSCRAPINPERCENT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_COSTELEMENT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_CREDITOR type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_CURRENCY type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_DELIVERYDURATIONINDAYS type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_DISCONTINUATIONGROUP type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_DISTRKEYCOMPCONSUMPTION type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_DOCNUMBER type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_DOCUMENTPART type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_DOCUMENTTYPE type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_DOCUMENTVERSION type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ENGINEERINGCHANGEDOCUMENT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_EXPLOSIONTYPE type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_FIXEDQUANTITY type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_FOLLOWUPGROUP type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_FORMULAKEY type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_GOODSRECEIPTDURATION type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_IDENTIFIERBOMITEM type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ISBOMRECURSIVEALLOWED type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ISBULKMATERIAL type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ISBULKMATERIALCOMPONENT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ISCLASSIFICATIONRELEVANT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ISENGINEERINGRELEVANT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ISMATERIALPROVISION type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ISNETSCRAP type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ISPMASSEMBLYRELEVANT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ISPRODUCTIONRELEVANT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ISSOFTWARECOMPONENT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ISSUBITEM type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_LEADTIMEOFFSET type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_MATERIALCOMPONENTPRICE type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_MATERIALGROUP type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_MATERIALISCOPRODUCT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_MATERIALPRICEUNITQTY type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_MULTIPLESELECTIONALLOWED type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_NUMBEROFVARIABLESIZEITEM type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_OBJECTTYPE type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_OPERATIONLEADTIMEOFFSET type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_OPERATIONSCRAPINPERCENT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_OPSLEADTIMEOFFSETUNIT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ORIGSALESORDERBOMITMCATEGORY type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ORIGSALESORDERBOMITMNUMBER type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ORIGSALESORDERBOMITM_1CC0BAA type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_PRELIMINARYMATERIAL type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_PRODORDERISSUELOCATION type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_PRODUCTIONSUPPLYAREA type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_PURCHASINGGROUP type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_PURCHASINGORGANIZATION type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_QUANTITYVARIABLESIZEITEM type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_REFERENCEPOINT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_REQUIREDCOMPONENT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_RESULTINGITEMCATEGORY type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_SIZE1 type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_SIZE2 type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_SIZE3 type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_SPECIALPROCUREMENTTYPE type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_UNITOFMEASUREFORSIZE1TO3 type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_UNITOFMEASUREFORVARSIZEITEM type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_USAGEPROBABILITYPERCENT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_VALIDITYENDDATE type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_VALIDITYSTARTDATE type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_VARIABLESIZECOMPUNIT_5D54C90 type SADL_GW_DYNAMIC_FIELD_PROPERTY,
    end of TS_C_BILLOFMATERIALITEMTPTYPE .
  types:
   TT_C_BILLOFMATERIALITEMTPTYPE type standard table of TS_C_BILLOFMATERIALITEMTPTYPE .
  types:
    begin of TS_C_BILLOFMATERIALPLANTTYPE.
      include type C_BILLOFMATERIALPLANT.
  types:
    end of TS_C_BILLOFMATERIALPLANTTYPE .
  types:
   TT_C_BILLOFMATERIALPLANTTYPE type standard table of TS_C_BILLOFMATERIALPLANTTYPE .
  types:
    begin of TS_C_BILLOFMATERIALSUBITEMSTPT.
      include type C_BILLOFMATERIALSUBITEMSTP.
  types:
      HASDRAFTENTITY type SDRAFT_FIELDS-HASDRAFTENTITY,
      DRAFTUUID type SDRAFT_FIELDS-DRAFTUUID,
      PARENTDRAFTUUID type SDRAFT_FIELDS-PARENTDRAFTUUID,
      ROOTDRAFTUUID type SDRAFT_FIELDS-ROOTDRAFTUUID,
      DRAFTENTITYCREATIONDATETIME type SDRAFT_FIELDS-DRAFTENTITYCREATIONDATETIME,
      DRAFTENTITYLASTCHANGEDATETIME type SDRAFT_FIELDS-DRAFTENTITYLASTCHANGEDATETIME,
      HASACTIVEENTITY type SDRAFT_FIELDS-HASACTIVEENTITY,
      ISACTIVEENTITY type SDRAFT_FIELDS-ISACTIVEENTITY,
      DRAFTENTITYOPERATIONCODE type SDRAFT_FIELDS-DRAFTENTITYOPERATIONCODE,
      A_DELETE_SUBITEM type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_PREPARATION type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_VALIDATION type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      F_BOMSUBITEMNUMBERVALUE type SADL_GW_DYNAMIC_FIELD_PROPERTY,
    end of TS_C_BILLOFMATERIALSUBITEMSTPT .
  types:
   TT_C_BILLOFMATERIALSUBITEMSTPT type standard table of TS_C_BILLOFMATERIALSUBITEMSTPT .
  types:
    begin of TS_C_BILLOFMATERIALTPTYPE.
      include type C_BILLOFMATERIALTP.
  types:
      HASDRAFTENTITY type SDRAFT_FIELDS-HASDRAFTENTITY,
      DRAFTUUID type SDRAFT_FIELDS-DRAFTUUID,
      DRAFTENTITYCREATIONDATETIME type SDRAFT_FIELDS-DRAFTENTITYCREATIONDATETIME,
      DRAFTENTITYLASTCHANGEDATETIME type SDRAFT_FIELDS-DRAFTENTITYLASTCHANGEDATETIME,
      HASACTIVEENTITY type SDRAFT_FIELDS-HASACTIVEENTITY,
      ISACTIVEENTITY type SDRAFT_FIELDS-ISACTIVEENTITY,
      DRAFTENTITYOPERATIONCODE type SDRAFT_FIELDS-DRAFTENTITYOPERATIONCODE,
      A_ACTIVATION type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_AINHANDOVER type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_ASSIGN_CN type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_ASSIGN_TO_CR type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_ASSIGN_TO_PLANT type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_CHECKSOFTWARE type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_COPYITEM type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_CREATEITEM type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_CREATE_ALTERNATIVE_BOM type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_CREATE_ITEM_GROUP type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_EDIT type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_GETCHANGERECORD type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_GET_CHANGED_OBOM_DRAFT_ITEMS type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_GET_COMPONENTS type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_GET_CR_ASSG_TO_BOM type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_OBSOLETEBOM type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_PREPARATION type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_RELEASEBOM type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_UNASSIGN_PLANT type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      A_VALIDATION type SADL_GW_DYNAMIC_ACTN_PROPERTY,
      F_BILLOFMATERIAL type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BILLOFMATERIALCATEGORY type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BILLOFMATERIALVARIANT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BILLOFMATERIALVARIANTFOREDIT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BILLOFMATERIALVARIANTUSAGE type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BILLOFMATERIALVERSION type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BILLOFMATERIALVERSIONFOREDIT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BOMALTERNATIVETEXT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BOMASSETNTWKHNDOVRISRELEVANT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BOMHEADERINTERNALCHANGECOUNT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BOMISARCHIVEDFORDELETION type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BOMVERSIONSTATUSDESCRIPTION type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_CHANGERECORD type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ENGINEERINGCHANGEDOCFOREDIT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ENGINEERINGCHANGEDOCUMENT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_HEADERVALIDITYENDDATE type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_HEADERVALIDITYSTARTDATE type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_LABORATORYORDESIGNOFFICE type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_MATERIAL type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_MATERIALFOREDIT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_MATERIALTOLOTSIZEQUANTITY type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_MATFROMLOTSIZEQUANTITY type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_NEWPLANT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_PLANT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_PLANTFOREDIT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_PURCHASEORDERBYCUSTOMER type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_SALESORDER type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_SALESORDERITEM type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_SOLDTOPARTY type SADL_GW_DYNAMIC_FIELD_PROPERTY,
    end of TS_C_BILLOFMATERIALTPTYPE .
  types:
   TT_C_BILLOFMATERIALTPTYPE type standard table of TS_C_BILLOFMATERIALTPTYPE .
  types:
    begin of TS_C_BILLOFMATERIALUSAGETYPE.
      include type C_BILLOFMATERIALUSAGE.
  types:
    end of TS_C_BILLOFMATERIALUSAGETYPE .
  types:
   TT_C_BILLOFMATERIALUSAGETYPE type standard table of TS_C_BILLOFMATERIALUSAGETYPE .
  types:
    begin of TS_C_BOMALTANDUSAGETYPE.
      include type C_BOMALTANDUSAGE.
  types:
    end of TS_C_BOMALTANDUSAGETYPE .
  types:
   TT_C_BOMALTANDUSAGETYPE type standard table of TS_C_BOMALTANDUSAGETYPE .
  types:
    begin of TS_C_BOMCOMPONENTVHTYPE.
      include type C_BOMCOMPONENTVH.
  types:
      F_BILLOFMATERIALCOMPONENT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_COMPONENTDESCRIPTION type SADL_GW_DYNAMIC_FIELD_PROPERTY,
    end of TS_C_BOMCOMPONENTVHTYPE .
  types:
   TT_C_BOMCOMPONENTVHTYPE type standard table of TS_C_BOMCOMPONENTVHTYPE .
  types:
    begin of TS_C_BOMCREATEFORUITYPE.
      include type C_BOMCREATEFORUI.
  types:
    end of TS_C_BOMCREATEFORUITYPE .
  types:
   TT_C_BOMCREATEFORUITYPE type standard table of TS_C_BOMCREATEFORUITYPE .
  types:
    begin of TS_C_BOMGROUPLINKSVHTYPE.
      include type C_BOMGROUPLINKSVH.
  types:
    end of TS_C_BOMGROUPLINKSVHTYPE .
  types:
   TT_C_BOMGROUPLINKSVHTYPE type standard table of TS_C_BOMGROUPLINKSVHTYPE .
  types:
    begin of TS_C_BOMITEMGROUPCREATEFORUITY.
      include type C_BOMITEMGROUPCREATEFORUI.
  types:
      F_BILLOFMATERIALCATEGORY type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BILLOFMATERIALVARIANT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BILLOFMATERIALVARIANTUSAGE type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_BILLOFMATERIALVERSION type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_ENGINEERINGCHANGEDOCUMENT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_MATERIAL type SADL_GW_DYNAMIC_FIELD_PROPERTY,
      F_PLANT type SADL_GW_DYNAMIC_FIELD_PROPERTY,
    end of TS_C_BOMITEMGROUPCREATEFORUITY .
  types:
   TT_C_BOMITEMGROUPCREATEFORUITY type standard table of TS_C_BOMITEMGROUPCREATEFORUITY .
  types:
    begin of TS_C_BOMMATERIALVHTYPE.
      include type C_BOMMATERIALVH.
  types:
    end of TS_C_BOMMATERIALVHTYPE .
  types:
   TT_C_BOMMATERIALVHTYPE type standard table of TS_C_BOMMATERIALVHTYPE .
  types:
    begin of TS_C_BOMMATPLANTVHTYPE.
      include type C_BOMMATPLANTVH.
  types:
    end of TS_C_BOMMATPLANTVHTYPE .
  types:
   TT_C_BOMMATPLANTVHTYPE type standard table of TS_C_BOMMATPLANTVHTYPE .
  types:
    begin of TS_C_CHANGEMASTERVHTYPE.
      include type C_CHANGEMASTERVH.
  types:
    end of TS_C_CHANGEMASTERVHTYPE .
  types:
   TT_C_CHANGEMASTERVHTYPE type standard table of TS_C_CHANGEMASTERVHTYPE .
  types:
    begin of TS_C_DOCINFOOBJECTTYPETYPE.
      include type C_DOCINFOOBJECTTYPE.
  types:
      T_LINKEDSAPOBJECT type I_DOCINFORECDOBJECTLINKTEXT-OBJECTDESCRIPTION,
    end of TS_C_DOCINFOOBJECTTYPETYPE .
  types:
   TT_C_DOCINFOOBJECTTYPETYPE type standard table of TS_C_DOCINFOOBJECTTYPETYPE .
  types:
    begin of TS_C_IMPCTMGMTCHANGERECORDVHTY.
      include type C_IMPCTMGMTCHANGERECORDVH.
  types:
    end of TS_C_IMPCTMGMTCHANGERECORDVHTY .
  types:
   TT_C_IMPCTMGMTCHANGERECORDVHTY type standard table of TS_C_IMPCTMGMTCHANGERECORDVHTY .
  types:
    begin of TS_C_MATERIALBOMTYPE.
      include type C_MATERIALBOM.
  types:
    end of TS_C_MATERIALBOMTYPE .
  types:
   TT_C_MATERIALBOMTYPE type standard table of TS_C_MATERIALBOMTYPE .
  types:
    begin of TS_C_MNGUNASSGDENGBOMCHGRECDTY.
      include type C_MNGUNASSGDENGBOMCHGRECD.
  types:
      T_CHANGERECORDCATEGORY type I_ISSUECATEGORYTXT-ISSUECATEGORYNAME,
      T_CHANGERECORDSTATUS type I_ISSACTYMGMTUSERSTATUS1T-ISSACTYMGMTUSERSTATUSTEXT,
      T_CHANGERECORDTYPE type I_CHANGERECORDTYPETEXT-CHANGERECORDTYPEDESC,
    end of TS_C_MNGUNASSGDENGBOMCHGRECDTY .
  types:
   TT_C_MNGUNASSGDENGBOMCHGRECDTY type standard table of TS_C_MNGUNASSGDENGBOMCHGRECDTY .
  types:
    begin of TS_C_SALESDOCUMENTITEMWLTYPE.
      include type C_SALESDOCUMENTITEMWL.
  types:
    end of TS_C_SALESDOCUMENTITEMWLTYPE .
  types:
   TT_C_SALESDOCUMENTITEMWLTYPE type standard table of TS_C_SALESDOCUMENTITEMWLTYPE .
  types:
    begin of TS_C_SDDOCUMENTVHTYPE.
      include type C_SDDOCUMENTVH.
  types:
    end of TS_C_SDDOCUMENTVHTYPE .
  types:
   TT_C_SDDOCUMENTVHTYPE type standard table of TS_C_SDDOCUMENTVHTYPE .
  types:
    begin of TS_I_ALTITEMSTRATEGYVHTYPE.
      include type I_ALTITEMSTRATEGYVH.
  types:
    end of TS_I_ALTITEMSTRATEGYVHTYPE .
  types:
   TT_I_ALTITEMSTRATEGYVHTYPE type standard table of TS_I_ALTITEMSTRATEGYVHTYPE .
  types:
    begin of TS_I_BILLOFMATERIALFORMULAVHTY.
      include type I_BILLOFMATERIALFORMULAVH.
  types:
    end of TS_I_BILLOFMATERIALFORMULAVHTY .
  types:
   TT_I_BILLOFMATERIALFORMULAVHTY type standard table of TS_I_BILLOFMATERIALFORMULAVHTY .
  types:
    begin of TS_I_BILLOFMATERIALITEMCATEGOR.
      include type I_BILLOFMATERIALITEMCATEGORY.
  types:
    end of TS_I_BILLOFMATERIALITEMCATEGOR .
  types:
   TT_I_BILLOFMATERIALITEMCATEGOR type standard table of TS_I_BILLOFMATERIALITEMCATEGOR .
  types:
    begin of TS_I_BILLOFMATERIALSTATUSTYPE.
      include type I_BILLOFMATERIALSTATUS.
  types:
      T_BILLOFMATERIALSTATUS type I_BILLOFMATERIALSTATUSTEXT-BILLOFMATERIALSTATUSTEXT,
    end of TS_I_BILLOFMATERIALSTATUSTYPE .
  types:
   TT_I_BILLOFMATERIALSTATUSTYPE type standard table of TS_I_BILLOFMATERIALSTATUSTYPE .
  types:
    begin of TS_I_BILLOFMATERIALSTATUSTEXTT.
      include type I_BILLOFMATERIALSTATUSTEXT.
  types:
    end of TS_I_BILLOFMATERIALSTATUSTEXTT .
  types:
   TT_I_BILLOFMATERIALSTATUSTEXTT type standard table of TS_I_BILLOFMATERIALSTATUSTEXTT .
  types:
    begin of TS_I_BILLOFMATERIALUOMVHTYPE.
      include type I_BILLOFMATERIALUOMVH.
  types:
    end of TS_I_BILLOFMATERIALUOMVHTYPE .
  types:
   TT_I_BILLOFMATERIALUOMVHTYPE type standard table of TS_I_BILLOFMATERIALUOMVHTYPE .
  types:
    begin of TS_I_BILLOFMATERIALUSAGETYPE.
      include type I_BILLOFMATERIALUSAGE.
  types:
    end of TS_I_BILLOFMATERIALUSAGETYPE .
  types:
   TT_I_BILLOFMATERIALUSAGETYPE type standard table of TS_I_BILLOFMATERIALUSAGETYPE .
  types:
    begin of TS_I_BILLOFMATERIALUSAGESTDVHT.
      include type I_BILLOFMATERIALUSAGESTDVH.
  types:
    end of TS_I_BILLOFMATERIALUSAGESTDVHT .
  types:
   TT_I_BILLOFMATERIALUSAGESTDVHT type standard table of TS_I_BILLOFMATERIALUSAGESTDVHT .
  types:
    begin of TS_I_BOMASSETNTWKMANUFACTURERV.
      include type I_BOMASSETNTWKMANUFACTURERVH.
  types:
    end of TS_I_BOMASSETNTWKMANUFACTURERV .
  types:
   TT_I_BOMASSETNTWKMANUFACTURERV type standard table of TS_I_BOMASSETNTWKMANUFACTURERV .
  types:
    begin of TS_I_BOMASSETNTWKTEMPLATEVHTYP.
      include type I_BOMASSETNTWKTEMPLATEVH.
  types:
    end of TS_I_BOMASSETNTWKTEMPLATEVHTYP .
  types:
   TT_I_BOMASSETNTWKTEMPLATEVHTYP type standard table of TS_I_BOMASSETNTWKTEMPLATEVHTYP .
  types:
    begin of TS_I_BOMCHANGEHISTORYTYPE.
      include type I_BOMCHANGEHISTORY.
  types:
    end of TS_I_BOMCHANGEHISTORYTYPE .
  types:
   TT_I_BOMCHANGEHISTORYTYPE type standard table of TS_I_BOMCHANGEHISTORYTYPE .
  types:
    begin of TS_I_BOMCHANGESTYPE.
      include type I_BOMCHANGES.
  types:
    end of TS_I_BOMCHANGESTYPE .
  types:
   TT_I_BOMCHANGESTYPE type standard table of TS_I_BOMCHANGESTYPE .
  types:
    begin of TS_I_BOMCOMPCATSTDVHTYPE.
      include type I_BOMCOMPCATSTDVH.
  types:
    end of TS_I_BOMCOMPCATSTDVHTYPE .
  types:
   TT_I_BOMCOMPCATSTDVHTYPE type standard table of TS_I_BOMCOMPCATSTDVHTYPE .
  types:
    begin of TS_I_BOMITEMCATEGORYVHTYPE.
      include type I_BOMITEMCATEGORYVH.
  types:
    end of TS_I_BOMITEMCATEGORYVHTYPE .
  types:
   TT_I_BOMITEMCATEGORYVHTYPE type standard table of TS_I_BOMITEMCATEGORYVHTYPE .
  types:
    begin of TS_I_BOMITEMCOSTINGRELEVANTTYP.
      include type I_BOMITEMCOSTINGRELEVANT.
  types:
    end of TS_I_BOMITEMCOSTINGRELEVANTTYP .
  types:
   TT_I_BOMITEMCOSTINGRELEVANTTYP type standard table of TS_I_BOMITEMCOSTINGRELEVANTTYP .
  types:
    begin of TS_I_BOMITEMSALESRELEVANTTYPE.
      include type I_BOMITEMSALESRELEVANT.
  types:
    end of TS_I_BOMITEMSALESRELEVANTTYPE .
  types:
   TT_I_BOMITEMSALESRELEVANTTYPE type standard table of TS_I_BOMITEMSALESRELEVANTTYPE .
  types:
    begin of TS_I_BOMITEMSPAREPARTTYPE.
      include type I_BOMITEMSPAREPART.
  types:
    end of TS_I_BOMITEMSPAREPARTTYPE .
  types:
   TT_I_BOMITEMSPAREPARTTYPE type standard table of TS_I_BOMITEMSPAREPARTTYPE .
  types:
    begin of TS_I_BOMVARIANTUSAGETYPE.
      include type I_BOMVARIANTUSAGE.
  types:
    end of TS_I_BOMVARIANTUSAGETYPE .
  types:
   TT_I_BOMVARIANTUSAGETYPE type standard table of TS_I_BOMVARIANTUSAGETYPE .
  types:
    begin of TS_I_CHANGEMASTERTYPE.
      include type I_CHANGEMASTER.
  types:
    end of TS_I_CHANGEMASTERTYPE .
  types:
   TT_I_CHANGEMASTERTYPE type standard table of TS_I_CHANGEMASTERTYPE .
  types:
    begin of TS_I_CHANGEMASTERFUNCTIONSTDVH.
      include type I_CHANGEMASTERFUNCTIONSTDVH.
  types:
      T_CHANGENUMBERFUNCTION type I_CHANGEMASTERFUNCTIONTEXT-CHANGENUMBERFUNCTIONTEXT,
    end of TS_I_CHANGEMASTERFUNCTIONSTDVH .
  types:
   TT_I_CHANGEMASTERFUNCTIONSTDVH type standard table of TS_I_CHANGEMASTERFUNCTIONSTDVH .
  types:
    begin of TS_I_CHANGEMASTERRELEASEKEYSTD.
      include type I_CHANGEMASTERRELEASEKEYSTDVH.
  types:
      T_CHANGENUMBERRELEASEKEY type I_CHANGEMASTERRELEASEKEYTEXT-CHANGENUMBERRELEASEKEYTEXT,
    end of TS_I_CHANGEMASTERRELEASEKEYSTD .
  types:
   TT_I_CHANGEMASTERRELEASEKEYSTD type standard table of TS_I_CHANGEMASTERRELEASEKEYSTD .
  types:
    begin of TS_I_CHANGEMASTERSTATUSSTDVHTY.
      include type I_CHANGEMASTERSTATUSSTDVH.
  types:
      T_CHANGENUMBERSTATUS type I_CHANGEMASTERSTATUSTEXT-CHANGENUMBERSTATUSTEXT,
    end of TS_I_CHANGEMASTERSTATUSSTDVHTY .
  types:
   TT_I_CHANGEMASTERSTATUSSTDVHTY type standard table of TS_I_CHANGEMASTERSTATUSSTDVHTY .
  types:
    begin of TS_I_CHANGEMASTERSTDVHTYPE.
      include type I_CHANGEMASTERSTDVH.
  types:
    end of TS_I_CHANGEMASTERSTDVHTYPE .
  types:
   TT_I_CHANGEMASTERSTDVHTYPE type standard table of TS_I_CHANGEMASTERSTDVHTYPE .
  types:
    begin of TS_I_CHANGEMASTERVHTYPE.
      include type I_CHANGEMASTERVH.
  types:
    end of TS_I_CHANGEMASTERVHTYPE .
  types:
   TT_I_CHANGEMASTERVHTYPE type standard table of TS_I_CHANGEMASTERVHTYPE .
  types:
    begin of TS_I_CHANGERECORDBSCTYPE.
      include type I_CHANGERECORDBSC.
  types:
    end of TS_I_CHANGERECORDBSCTYPE .
  types:
   TT_I_CHANGERECORDBSCTYPE type standard table of TS_I_CHANGERECORDBSCTYPE .
  types:
    begin of TS_I_CHGRECDREFENGBOMBSCTYPE.
      include type I_CHGRECDREFENGBOMBSC.
  types:
    end of TS_I_CHGRECDREFENGBOMBSCTYPE .
  types:
   TT_I_CHGRECDREFENGBOMBSCTYPE type standard table of TS_I_CHGRECDREFENGBOMBSCTYPE .
  types:
    begin of TS_I_CHGRECDREFMFGBOMBSCTYPE.
      include type I_CHGRECDREFMFGBOMBSC.
  types:
    end of TS_I_CHGRECDREFMFGBOMBSCTYPE .
  types:
   TT_I_CHGRECDREFMFGBOMBSCTYPE type standard table of TS_I_CHGRECDREFMFGBOMBSCTYPE .
  types:
    begin of TS_I_CLFNCLASSVHTYPE.
      include type I_CLFNCLASSVH.
  types:
      T_CLASS type I_CLFNCLASSDESCRIPTION-CLASSDESCRIPTION,
    end of TS_I_CLFNCLASSVHTYPE .
  types:
   TT_I_CLFNCLASSVHTYPE type standard table of TS_I_CLFNCLASSVHTYPE .
  types:
    begin of TS_I_COSTELEMENTVHTYPE.
      include type I_COSTELEMENTVH.
  types:
    end of TS_I_COSTELEMENTVHTYPE .
  types:
   TT_I_COSTELEMENTVHTYPE type standard table of TS_I_COSTELEMENTVHTYPE .
  types:
    begin of TS_I_CURRENCYTYPE.
      include type I_CURRENCY.
  types:
      T_CURRENCY type I_CURRENCYTEXT-CURRENCYNAME,
    end of TS_I_CURRENCYTYPE .
  types:
   TT_I_CURRENCYTYPE type standard table of TS_I_CURRENCYTYPE .
  types:
    begin of TS_I_CURRENCYSTDVHTYPE.
      include type I_CURRENCYSTDVH.
  types:
      T_CURRENCY type I_CURRENCYTEXT-CURRENCYNAME,
    end of TS_I_CURRENCYSTDVHTYPE .
  types:
   TT_I_CURRENCYSTDVHTYPE type standard table of TS_I_CURRENCYSTDVHTYPE .
  types:
    begin of TS_I_CUSTOMERTYPE.
      include type I_CUSTOMER.
  types:
      T_CUSTOMERCLASSIFICATION type I_CUSTOMERCLASSIFICATIONTEXT-CUSTOMERCLASSIFICATIONDESC,
    end of TS_I_CUSTOMERTYPE .
  types:
   TT_I_CUSTOMERTYPE type standard table of TS_I_CUSTOMERTYPE .
  types:
    begin of TS_I_CUSTOMER_VHTYPE.
      include type I_CUSTOMER_VH.
  types:
    end of TS_I_CUSTOMER_VHTYPE .
  types:
   TT_I_CUSTOMER_VHTYPE type standard table of TS_I_CUSTOMER_VHTYPE .
  types:
    begin of TS_I_DISTRIBUTIONKEYVHTYPE.
      include type I_DISTRIBUTIONKEYVH.
  types:
    end of TS_I_DISTRIBUTIONKEYVHTYPE .
  types:
   TT_I_DISTRIBUTIONKEYVHTYPE type standard table of TS_I_DISTRIBUTIONKEYVHTYPE .
  types:
    begin of TS_I_DOCINFORECDTYPE.
      include type I_DOCINFORECD.
  types:
    end of TS_I_DOCINFORECDTYPE .
  types:
   TT_I_DOCINFORECDTYPE type standard table of TS_I_DOCINFORECDTYPE .
  types:
    begin of TS_I_DOCUMENTINFORECORDDOCPRTV.
      include type I_DOCUMENTINFORECORDDOCPRTVH.
  types:
      T_DOCUMENTINFORECORDDOCTYPE type I_DOCUMENTINFORECORDDOCTYPET-DOCUMENTTYPEDESCRIPTION,
    end of TS_I_DOCUMENTINFORECORDDOCPRTV .
  types:
   TT_I_DOCUMENTINFORECORDDOCPRTV type standard table of TS_I_DOCUMENTINFORECORDDOCPRTV .
  types:
   TS_I_DRAFTADMINISTRATIVEDATATY type I_DRAFTADMINISTRATIVEDATA .
  types:
   TT_I_DRAFTADMINISTRATIVEDATATY type standard table of TS_I_DRAFTADMINISTRATIVEDATATY .
  types:
    begin of TS_I_EXPLOSIONTYPEVHTYPE.
      include type I_EXPLOSIONTYPEVH.
  types:
    end of TS_I_EXPLOSIONTYPEVHTYPE .
  types:
   TT_I_EXPLOSIONTYPEVHTYPE type standard table of TS_I_EXPLOSIONTYPEVHTYPE .
  types:
    begin of TS_I_LABORATORYORDESIGNOFFICEV.
      include type I_LABORATORYORDESIGNOFFICEVH.
  types:
    end of TS_I_LABORATORYORDESIGNOFFICEV .
  types:
   TT_I_LABORATORYORDESIGNOFFICEV type standard table of TS_I_LABORATORYORDESIGNOFFICEV .
  types:
    begin of TS_I_LOGACCMOBJECTTYPEACTIVETY.
      include type I_LOGACCMOBJECTTYPEACTIVE.
  types:
    end of TS_I_LOGACCMOBJECTTYPEACTIVETY .
  types:
   TT_I_LOGACCMOBJECTTYPEACTIVETY type standard table of TS_I_LOGACCMOBJECTTYPEACTIVETY .
  types:
    begin of TS_I_LOGACCMOBJSECUREIDASSGMTT.
      include type I_LOGACCMOBJSECUREIDASSGMT.
  types:
    end of TS_I_LOGACCMOBJSECUREIDASSGMTT .
  types:
   TT_I_LOGACCMOBJSECUREIDASSGMTT type standard table of TS_I_LOGACCMOBJSECUREIDASSGMTT .
  types:
    begin of TS_I_MATERIALTYPE.
      include type I_MATERIAL.
  types:
      T_MATERIAL type I_MATERIALTEXT-MATERIALNAME,
    end of TS_I_MATERIALTYPE .
  types:
   TT_I_MATERIALTYPE type standard table of TS_I_MATERIALTYPE .
  types:
    begin of TS_I_MATERIALSTDVHTYPE.
      include type I_MATERIALSTDVH.
  types:
      T_MATERIAL type I_MATERIALTEXT-MATERIALNAME,
    end of TS_I_MATERIALSTDVHTYPE .
  types:
   TT_I_MATERIALSTDVHTYPE type standard table of TS_I_MATERIALSTDVHTYPE .
  types:
    begin of TS_I_MATERIALTEXTTYPE.
      include type I_MATERIALTEXT.
  types:
    end of TS_I_MATERIALTEXTTYPE .
  types:
   TT_I_MATERIALTEXTTYPE type standard table of TS_I_MATERIALTEXTTYPE .
  types:
    begin of TS_I_MATPROVISIONINDICATORVHTY.
      include type I_MATPROVISIONINDICATORVH.
  types:
    end of TS_I_MATPROVISIONINDICATORVHTY .
  types:
   TT_I_MATPROVISIONINDICATORVHTY type standard table of TS_I_MATPROVISIONINDICATORVHTY .
  types:
    begin of TS_I_PLANTSTDVHTYPE.
      include type I_PLANTSTDVH.
  types:
    end of TS_I_PLANTSTDVHTYPE .
  types:
   TT_I_PLANTSTDVHTYPE type standard table of TS_I_PLANTSTDVHTYPE .
  types:
    begin of TS_I_PRODUCTTYPE.
      include type I_PRODUCT.
  types:
      T_PRODUCT type I_PRODUCTTEXT-PRODUCTNAME,
      T_PRODUCTTYPE type I_PRODUCTTYPETEXT-MATERIALTYPENAME,
      T_CROSSPLANTSTATUS type I_PRODUCTSTATUSTEXT-MATERIALUSABILITYPROFILENAME,
      T_WEIGHTUNIT type I_UNITOFMEASURETEXT-UNITOFMEASURELONGNAME,
      T_PRODUCTGROUP type I_PRODUCTGROUPTEXT_2-PRODUCTGROUPNAME,
      T_BASEUNIT type I_UNITOFMEASURETEXT-UNITOFMEASURELONGNAME,
      T_ITEMCATEGORYGROUP type I_ITEMCATEGORYGROUPTEXT-ITEMCATEGORYGROUPNAME,
      T_PRODUCTHIERARCHY type I_PRODUCTHIERARCHYTEXT-PRODUCTHIERARCHYTEXT,
      T_DIVISION type I_DIVISIONTEXT-DIVISIONNAME,
      T_VOLUMEUNIT type I_UNITOFMEASURETEXT-UNITOFMEASURELONGNAME,
      T_ANPCODE type I_BR_ANPCODETEXT-BR_ANPCODEDESC,
      T_PRODUCTCATEGORY type I_PRODUCTCATEGORYTEXT-NAME,
      T_BRAND type I_BRANDTEXT-BRANDNAME,
      T_INTERNATIONALARTICLE_DC14718 type I_INTNTNLARTNMBCATTEXT-INTLARTICLENUMBERCATNAME,
      T_EXTERNALPRODUCTGROUP type I_EXTPRODGRPTEXT-EXTERNALPRODUCTGROUPNAME,
      T_CROSSPLANTCONFIGURAB_E2AD18B type I_PRODUCTDESCRIPTION-PRODUCTDESCRIPTION,
      T_HANDLINGINDICATOR type I_EWM_MATERIALHANDLINGT-MATERIALHANDLINGTEXT,
      T_WAREHOUSEPRODUCTGROUP type I_EWM_WAREHOUSEMATERIALGROUPT-WAREHOUSEPRODUCTGROUPTEXT,
      T_WAREHOUSESTORAGECONDITION type I_EWM_WHSESTORAGECONDITIONT-WAREHOUSESTORAGECONDITIONTEXT,
      T_STANDARDHANDLINGUNITTYPE type I_EWM_HANDLINGUNITTYPET-HANDLINGUNITTYPETEXT,
      T_SERIALNUMBERPROFILE type I_EWM_SERIALNUMBERPROFILET-SERIALNUMBERPROFILENAME,
      T_ADJUSTMENTPROFILE type I_PRODEWMADJMTPROFILETEXT-EWMADJUSTMENTPROFILETEXT,
      T_TIMEUNITFORQUARANTINEPERIOD type I_UNITOFMEASURETEXT-UNITOFMEASURELONGNAME,
      T_QUALITYINSPECTIONGROUP type I_EWM_QUALITYINSPECTIONGROUPT-QUALITYINSPECTIONGROUPTEXT,
      T_HANDLINGUNITTYPE type I_EWM_HANDLINGUNITTYPET-HANDLINGUNITTYPETEXT,
      T_UNITFORMAXPACKAGINGD_082CAC1 type I_UNITOFMEASURETEXT-UNITOFMEASURELONGNAME,
      T_PRODUCTMEASUREMENTUNIT type I_UNITOFMEASURETEXT-UNITOFMEASURELONGNAME,
      T_CONTENTUNIT type I_UNITOFMEASURETEXT-UNITOFMEASURELONGNAME,
      T_ASSORTMENTLISTTYPE type I_ASSORTMENTLISTTYPET-ASSORTMENTLISTTYPENAME,
      T_ISCHEMICALCOMPLIANCERELEVANT type I_CHEMICALCOMPLIANCERLVTTEXT-NAME,
    end of TS_I_PRODUCTTYPE .
  types:
   TT_I_PRODUCTTYPE type standard table of TS_I_PRODUCTTYPE .
  types:
    begin of TS_I_PRODUCTGROUP_2TYPE.
      include type I_PRODUCTGROUP_2.
  types:
      T_PRODUCTGROUP type I_PRODUCTGROUPTEXT_2-PRODUCTGROUPNAME,
    end of TS_I_PRODUCTGROUP_2TYPE .
  types:
   TT_I_PRODUCTGROUP_2TYPE type standard table of TS_I_PRODUCTGROUP_2TYPE .
  types:
    begin of TS_I_PRODUCTINTERNALTYPE.
      include type I_PRODUCTINTERNAL.
  types:
    end of TS_I_PRODUCTINTERNALTYPE .
  types:
   TT_I_PRODUCTINTERNALTYPE type standard table of TS_I_PRODUCTINTERNALTYPE .
  types:
    begin of TS_I_PRODUCTIONSTORAGELOCATION.
      include type I_PRODUCTIONSTORAGELOCATIONVH.
  types:
    end of TS_I_PRODUCTIONSTORAGELOCATION .
  types:
   TT_I_PRODUCTIONSTORAGELOCATION type standard table of TS_I_PRODUCTIONSTORAGELOCATION .
  types:
    begin of TS_I_PRODUCTIONSUPPLYAREAVHTYP.
      include type I_PRODUCTIONSUPPLYAREAVH.
  types:
    end of TS_I_PRODUCTIONSUPPLYAREAVHTYP .
  types:
   TT_I_PRODUCTIONSUPPLYAREAVHTYP type standard table of TS_I_PRODUCTIONSUPPLYAREAVHTYP .
  types:
    begin of TS_I_PRODUCTSTDVHTYPE.
      include type I_PRODUCTSTDVH.
  types:
      T_PRODUCT type I_PRODUCTTEXT-PRODUCTNAME,
    end of TS_I_PRODUCTSTDVHTYPE .
  types:
   TT_I_PRODUCTSTDVHTYPE type standard table of TS_I_PRODUCTSTDVHTYPE .
  types:
    begin of TS_I_PRODUCTVHTYPE.
      include type I_PRODUCTVH.
  types:
      T_PRODUCT type I_PRODUCTDESCRIPTION-PRODUCTDESCRIPTION,
    end of TS_I_PRODUCTVHTYPE .
  types:
   TT_I_PRODUCTVHTYPE type standard table of TS_I_PRODUCTVHTYPE .
  types:
    begin of TS_I_PURCHASINGGROUPTYPE.
      include type I_PURCHASINGGROUP.
  types:
    end of TS_I_PURCHASINGGROUPTYPE .
  types:
   TT_I_PURCHASINGGROUPTYPE type standard table of TS_I_PURCHASINGGROUPTYPE .
  types:
    begin of TS_I_PURCHASINGORGANIZATIONTYP.
      include type I_PURCHASINGORGANIZATION.
  types:
    end of TS_I_PURCHASINGORGANIZATIONTYP .
  types:
   TT_I_PURCHASINGORGANIZATIONTYP type standard table of TS_I_PURCHASINGORGANIZATIONTYP .
  types:
    begin of TS_I_REFERENCEPOINTVHTYPE.
      include type I_REFERENCEPOINTVH.
  types:
    end of TS_I_REFERENCEPOINTVHTYPE .
  types:
   TT_I_REFERENCEPOINTVHTYPE type standard table of TS_I_REFERENCEPOINTVHTYPE .
  types:
    begin of TS_I_SPECIALPROCUREMENTTYPETYP.
      include type I_SPECIALPROCUREMENTTYPE.
  types:
    end of TS_I_SPECIALPROCUREMENTTYPETYP .
  types:
   TT_I_SPECIALPROCUREMENTTYPETYP type standard table of TS_I_SPECIALPROCUREMENTTYPETYP .
  types:
    begin of TS_I_SUPPLIER_VHTYPE.
      include type I_SUPPLIER_VH.
  types:
    end of TS_I_SUPPLIER_VHTYPE .
  types:
   TT_I_SUPPLIER_VHTYPE type standard table of TS_I_SUPPLIER_VHTYPE .
  types:
    begin of TS_I_UNITIZEDMATERIALTYPE.
      include type I_UNITIZEDMATERIAL.
  types:
      T_MATERIAL type I_MATERIALTEXT-MATERIALNAME,
    end of TS_I_UNITIZEDMATERIALTYPE .
  types:
   TT_I_UNITIZEDMATERIALTYPE type standard table of TS_I_UNITIZEDMATERIALTYPE .
  types:
    begin of TS_I_UNITOFMEASURETYPE.
      include type I_UNITOFMEASURE.
  types:
      T_UNITOFMEASURE type I_UNITOFMEASURETEXT-UNITOFMEASURELONGNAME,
    end of TS_I_UNITOFMEASURETYPE .
  types:
   TT_I_UNITOFMEASURETYPE type standard table of TS_I_UNITOFMEASURETYPE .
  types:
    begin of TS_I_UNITOFMEASURESTDVHTYPE.
      include type I_UNITOFMEASURESTDVH.
  types:
    end of TS_I_UNITOFMEASURESTDVHTYPE .
  types:
   TT_I_UNITOFMEASURESTDVHTYPE type standard table of TS_I_UNITOFMEASURESTDVHTYPE .
  types:
    begin of TS_I_UNITOFMEASURETIMEVHTYPE.
      include type I_UNITOFMEASURETIMEVH.
  types:
    end of TS_I_UNITOFMEASURETIMEVHTYPE .
  types:
   TT_I_UNITOFMEASURETIMEVHTYPE type standard table of TS_I_UNITOFMEASURETIMEVHTYPE .
  types:
    begin of TS_I_VERSIONSTATUSTYPE.
      include type I_VERSIONSTATUS.
  types:
    end of TS_I_VERSIONSTATUSTYPE .
  types:
   TT_I_VERSIONSTATUSTYPE type standard table of TS_I_VERSIONSTATUSTYPE .

  constants GC_I_MATERIALSTDVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_MaterialStdVHType' ##NO_TEXT.
  constants GC_I_LOGACCMOBJSECUREIDASSGMTT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_LogAccMObjSecureIDAssgmtType' ##NO_TEXT.
  constants GC_I_LOGACCMOBJECTTYPEACTIVETY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_LogAccMObjectTypeActiveType' ##NO_TEXT.
  constants GC_I_LABORATORYORDESIGNOFFICEV type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_LaboratoryOrDesignOfficeVHType' ##NO_TEXT.
  constants GC_I_EXPLOSIONTYPEVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ExplosionTypeVHType' ##NO_TEXT.
  constants GC_I_DRAFTADMINISTRATIVEDATATY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_DraftAdministrativeDataType' ##NO_TEXT.
  constants GC_I_DOCUMENTINFORECORDDOCPRTV type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_DocumentInfoRecordDocPrtVHType' ##NO_TEXT.
  constants GC_I_DOCINFORECDTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_DocInfoRecdType' ##NO_TEXT.
  constants GC_I_DISTRIBUTIONKEYVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_DistributionKeyVHType' ##NO_TEXT.
  constants GC_I_CUSTOMER_VHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_Customer_VHType' ##NO_TEXT.
  constants GC_I_CUSTOMERTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CustomerType' ##NO_TEXT.
  constants GC_I_CURRENCYTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CurrencyType' ##NO_TEXT.
  constants GC_I_CURRENCYSTDVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CurrencyStdVHType' ##NO_TEXT.
  constants GC_I_COSTELEMENTVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_CostElementVHType' ##NO_TEXT.
  constants GC_I_CLFNCLASSVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ClfnClassVHType' ##NO_TEXT.
  constants GC_I_CHGRECDREFMFGBOMBSCTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ChgRecdRefMfgBOMBscType' ##NO_TEXT.
  constants GC_I_CHGRECDREFENGBOMBSCTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ChgRecdRefEngBOMBscType' ##NO_TEXT.
  constants GC_I_CHANGERECORDBSCTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ChangeRecordBscType' ##NO_TEXT.
  constants GC_I_CHANGEMASTERVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ChangeMasterVHType' ##NO_TEXT.
  constants GC_I_CHANGEMASTERTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ChangeMasterType' ##NO_TEXT.
  constants GC_I_CHANGEMASTERSTDVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ChangeMasterStdVHType' ##NO_TEXT.
  constants GC_I_CHANGEMASTERSTATUSSTDVHTY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ChangeMasterStatusStdVHType' ##NO_TEXT.
  constants GC_I_MATERIALTEXTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_MaterialTextType' ##NO_TEXT.
  constants GC_VERSIONCONTROL type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'VersionControl' ##NO_TEXT.
  constants GC_MANDATORYCRASSIGNMENT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'MandatoryCRAssignment' ##NO_TEXT.
  constants GC_I_VERSIONSTATUSTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_VersionStatusType' ##NO_TEXT.
  constants GC_I_UNITOFMEASURETYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_UnitOfMeasureType' ##NO_TEXT.
  constants GC_I_UNITOFMEASURETIMEVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_UnitOfMeasureTimeVHType' ##NO_TEXT.
  constants GC_I_UNITOFMEASURESTDVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_UnitOfMeasureStdVHType' ##NO_TEXT.
  constants GC_I_UNITIZEDMATERIALTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_UnitizedMaterialType' ##NO_TEXT.
  constants GC_I_SUPPLIER_VHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_Supplier_VHType' ##NO_TEXT.
  constants GC_I_SPECIALPROCUREMENTTYPETYP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_SpecialProcurementTypeType' ##NO_TEXT.
  constants GC_I_REFERENCEPOINTVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ReferencePointVHType' ##NO_TEXT.
  constants GC_I_PURCHASINGORGANIZATIONTYP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_PurchasingOrganizationType' ##NO_TEXT.
  constants GC_I_PURCHASINGGROUPTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_PurchasingGroupType' ##NO_TEXT.
  constants GC_I_PRODUCTVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ProductVHType' ##NO_TEXT.
  constants GC_I_PRODUCTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ProductType' ##NO_TEXT.
  constants GC_I_PRODUCTSTDVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ProductStdVHType' ##NO_TEXT.
  constants GC_I_PRODUCTIONSUPPLYAREAVHTYP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ProductionSupplyAreaVHType' ##NO_TEXT.
  constants GC_I_PRODUCTIONSTORAGELOCATION type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ProductionStorageLocationVHType' ##NO_TEXT.
  constants GC_I_PRODUCTINTERNALTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ProductInternalType' ##NO_TEXT.
  constants GC_I_PRODUCTGROUP_2TYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ProductGroup_2Type' ##NO_TEXT.
  constants GC_I_PLANTSTDVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_PlantStdVHType' ##NO_TEXT.
  constants GC_I_MATPROVISIONINDICATORVHTY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_MatProvisionIndicatorVHType' ##NO_TEXT.
  constants GC_I_MATERIALTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_MaterialType' ##NO_TEXT.
  constants GC_I_CHANGEMASTERRELEASEKEYSTD type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ChangeMasterReleaseKeyStdVHType' ##NO_TEXT.
  constants GC_EFFECTIVITYPARAMETERS type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'EffectivityParameters' ##NO_TEXT.
  constants GC_C_SDDOCUMENTVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_SDDocumentVHType' ##NO_TEXT.
  constants GC_C_SALESDOCUMENTITEMWLTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_SalesDocumentItemWlType' ##NO_TEXT.
  constants GC_C_MNGUNASSGDENGBOMCHGRECDTY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_MngUnassgdEngBOMChgRecdType' ##NO_TEXT.
  constants GC_C_MATERIALBOMTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_MaterialBOMType' ##NO_TEXT.
  constants GC_C_IMPCTMGMTCHANGERECORDVHTY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_ImpctMgmtChangeRecordVHType' ##NO_TEXT.
  constants GC_C_DOCINFOOBJECTTYPETYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_DocInfoObjectTypeType' ##NO_TEXT.
  constants GC_C_CHANGEMASTERVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_ChangeMasterVHType' ##NO_TEXT.
  constants GC_C_BOMMATPLANTVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_BOMMatPlantVHType' ##NO_TEXT.
  constants GC_C_BOMMATERIALVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_BOMMaterialVHType' ##NO_TEXT.
  constants GC_C_BOMITEMGROUPCREATEFORUITY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_BOMItemGroupCreateForUIType' ##NO_TEXT.
  constants GC_C_BOMGROUPLINKSVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_BOMGroupLinksVHType' ##NO_TEXT.
  constants GC_C_BOMCREATEFORUITYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_BOMCreateForUIType' ##NO_TEXT.
  constants GC_C_BOMCOMPONENTVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_BOMComponentVHType' ##NO_TEXT.
  constants GC_C_BOMALTANDUSAGETYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_BOMAltAndUsageType' ##NO_TEXT.
  constants GC_C_BILLOFMATERIALUSAGETYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_BillOfMaterialUsageType' ##NO_TEXT.
  constants GC_C_BILLOFMATERIALTPTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_BillOfMaterialTPType' ##NO_TEXT.
  constants GC_C_BILLOFMATERIALSUBITEMSTPT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_BillOfMaterialSubItemsTPType' ##NO_TEXT.
  constants GC_C_BILLOFMATERIALPLANTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_BillOfMaterialPlantType' ##NO_TEXT.
  constants GC_C_BILLOFMATERIALITEMTPTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'C_BillOfMaterialItemTPType' ##NO_TEXT.
  constants GC_CHANGENUMBER type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'ChangeNumber' ##NO_TEXT.
  constants GC_ADDITIONALCONTROLDATA type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'AdditionalControlData' ##NO_TEXT.
  constants GC_ENGINEERINGCHANGEDOCUMENT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'EngineeringChangeDocument' ##NO_TEXT.
  constants GC_I_CHANGEMASTERFUNCTIONSTDVH type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_ChangeMasterFunctionStdVHType' ##NO_TEXT.
  constants GC_I_BOMVARIANTUSAGETYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_BOMVariantUsageType' ##NO_TEXT.
  constants GC_I_BOMITEMSPAREPARTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_BOMItemSparePartType' ##NO_TEXT.
  constants GC_I_BOMITEMSALESRELEVANTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_BOMItemSalesRelevantType' ##NO_TEXT.
  constants GC_I_BOMITEMCOSTINGRELEVANTTYP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_BOMItemCostingRelevantType' ##NO_TEXT.
  constants GC_I_BOMITEMCATEGORYVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_BOMItemCategoryVHType' ##NO_TEXT.
  constants GC_I_BOMCOMPCATSTDVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_BOMCompCatStdVHType' ##NO_TEXT.
  constants GC_I_BOMCHANGESTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_BomChangesType' ##NO_TEXT.
  constants GC_I_BOMCHANGEHISTORYTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_BOMChangeHistoryType' ##NO_TEXT.
  constants GC_I_BOMASSETNTWKTEMPLATEVHTYP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_BOMAssetNtwkTemplateVHType' ##NO_TEXT.
  constants GC_I_BOMASSETNTWKMANUFACTURERV type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_BOMAssetNtwkManufacturerVHType' ##NO_TEXT.
  constants GC_I_BILLOFMATERIALUSAGETYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_BillOfMaterialUsageType' ##NO_TEXT.
  constants GC_I_BILLOFMATERIALUSAGESTDVHT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_BillOfMaterialUsageStdVHType' ##NO_TEXT.
  constants GC_I_BILLOFMATERIALUOMVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_BillOfMaterialUoMVHType' ##NO_TEXT.
  constants GC_I_BILLOFMATERIALSTATUSTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_BillOfMaterialStatusType' ##NO_TEXT.
  constants GC_I_BILLOFMATERIALSTATUSTEXTT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_BillOfMaterialStatusTextType' ##NO_TEXT.
  constants GC_I_BILLOFMATERIALITEMCATEGOR type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_BillOfMaterialItemCategoryType' ##NO_TEXT.
  constants GC_I_BILLOFMATERIALFORMULAVHTY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_BillOfMaterialFormulaVHType' ##NO_TEXT.
  constants GC_I_ALTITEMSTRATEGYVHTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'I_AltItemStrategyVHType' ##NO_TEXT.
  constants GC_IMPACTANALYSISSCENARIO type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'ImpactAnalysisScenario' ##NO_TEXT.
  constants GC_IMPACTANALYSISNODE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'ImpactAnalysisNode' ##NO_TEXT.

  methods LOAD_TEXT_ELEMENTS
  final
    returning
      value(RT_TEXT_ELEMENTS) type TT_TEXT_ELEMENTS
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .

  methods DEFINE
    redefinition .
  methods GET_LAST_MODIFIED
    redefinition .